[package]
name = "svsm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stage2"
path = "src/stage2.rs"
test = false

[[bin]]
name = "svsm"
path = "src/svsm.rs"
test = false

[lib]
test = true
doctest = true

[dependencies]
bootlib.workspace = true
cpuarch.workspace = true
elf.workspace = true
syscall.workspace = true

aes-gcm = { workspace = true, features = ["aes", "alloc"] }
bitflags.workspace = true
#getrandom.workspace = true
#num-bigint = { path="../../num-bigint", version = "0.8.4", default-features = false, features = ["prime"], package = "num-bigint-dig"}
#num-traits = { version = "0.2.19", default-features = false, features = [] }
#getrandom = { version = "0.2.15", default-features = false, features = ["rdrand"]}
#rsa = { version= "0.9.6", default-features = false, features = [] }
#rsa = { path = "../../RSA", default-features = false, features = [] }
#sha2 = { version="0.10.8", default_features = false, features = ["force-soft"]}
gdbstub = { workspace = true, optional = true }
gdbstub_arch = { workspace = true, optional = true }
igvm_defs = { workspace = true, features = ["unstable"] }
intrusive-collections.workspace = true
log = { workspace = true, features = ["max_level_info", "release_max_level_info"] }
packit.workspace = true
libmstpm = { workspace = true, optional = true }

[target."x86_64-unknown-none".dev-dependencies]
test.workspace = true

[features]
default = ["mstpm"]
default-test = []
enable-gdb = ["dep:gdbstub", "dep:gdbstub_arch"]
mstpm = ["dep:libmstpm"]

[dev-dependencies]

[lints]
workspace = true
